site_name: Хаб-знаний
theme:
  language: ru
  name: material
  palette:
    scheme: slate
    primary: '#002B5C'
    accent: '#0053A0'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs
    - navigation.top
    - content.tabs
    - content.code.annotate
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tooltips #Для С помощью <abbr title="Система контроля версий">SCV</abbr> можно управлять кодом.
  #logo: assets/logo.png

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: table
      line_spans: "__line__"
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - Главная: index.md
  - Студенту:
    - "Стипендии и иные виды материальной поддержки": SPHTI_www\Стипендии и иные виды материальной поддержки.md
    - "Офицальный сайт": https://www.sphti.ru
  - Git Система:
    - Глава 1:
      - "1.1 Скачивание и установка Git": Git-system/Глава 1/1.1 Скачивание и установка Git.md
      - "1.2 Основные концепции Git": Git-system/Глава 1/1.2 Основные концепции Git.md
      - "1.3 Руководство по использованию Git-платформы": Git-system/Глава 1/1.3 Руководство по использованию Git-платформы.md
    - Глава 2:
      - "2.1 Основные команды и способы работы с локальным Git": Git-system/Глава 2/2.1 Основные команды и способы работы с локальным Git.md
      - "2.2 Пример работы с локальным Git": Git-system/Глава 2/2.2 Пример работы с локальным Git.md
    - Глава 3:
      - "3.1 Основные команды и способы работы с удаленным Git": Git-system/Глава 3/3.1 Основные команды и способы работы с удаленным Git.md
      - "3.2 Пример работы с удаленным Git": Git-system/Глава 3/3.2 Пример работы с удаленным Git.md
    - Глава 4:
      - "4.1 Интеграция в MVS локального Git": Git-system/Глава 4/4.1 Интеграция в MVS локального Git.md
      - "4.2 Интеграция в MVS удаленного Git": Git-system/Глава 4/4.2 Интеграция в MVS удаленного Git.md
    - Дополнительно:
      - "Рекомендации по ведению репозитория": Git-system/Дополнительно/Рекомендации по ведению репозитория.md
  - Инструменты разработки:
      - "VS Code":
          - "Введение в VS Code":
              - "Что такое VS Code?": DevOps/VS Code/Что такое VS Code.md
          - "Установка и настройка VS Code":
              - "Скачивание и установка VS Code": DevOps/VS Code/Скачивание и установка VS Code.md