site_name: Wiki PWFoox
theme:
  name: material
  palette:
    scheme: slate
    primary: '#002B5C'
    accent: '#0053A0'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
  #logo: assets/logo.png

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: table
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - Главная: index.md
  - Глава 1:
    - "1.1 Скачивание и установка Git": Глава 1/1.1 Скачивание и установка Git.md
    - "1.2 Основные концепции Git": Глава 1/1.2 Основные концепции Git.md
    - "1.3 Руководство по использованию Git-платформы": Глава 1/1.3 Руководство по использованию Git-платформы.md
  - Глава 2:
    - "2.1 Основные команды и способы работы с локальным Git": Глава 2/2.1 Основные команды и способы работы с локальным Git.md
    - "2.2 Пример работы с локальным Git": Глава 2/2.2 Пример работы с локальным Git.md
  - Глава 3:
    - "3.1 Основные команды и способы работы с удаленным Git": Глава 3/3.1 Основные команды и способы работы с удаленным Git.md
    - "3.2 Пример работы с удаленным Git": Глава 3/3.2 Пример работы с удаленным Git.md
  - Глава 4:
    - "4.1 Интеграция в MVS локального Git": Глава 4/4.1 Интеграция в MVS локального Git.md
    - "4.2 Интеграция в MVS удаленного Git": Глава 4/4.2 Интеграция в MVS удаленного Git.md
  - Дополнительно:
    - "Рекомендации по ведению репозитория": Дополнительно/Рекомендации по ведению репозитория.md